packages:
  - apps/*
  - packages/*
  - "!**/test/**"
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - lefthook
catalog:
  "@biomejs/biome": 2.3.3
  "@microsoft/api-extractor": 7.54.0
  "@rslib/core": 0.17.0
  "@rsbuild/plugin-react": 1.4.1
  "@typescript/native-preview": 7.0.0-dev.20251104.1
  "@vitejs/plugin-react": 5.1.0
  "@vitest/browser-playwright": 4.0.7
  "@vitest/coverage-v8": 4.0.7
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  lefthook: 2.0.2
  react: 19.2.0
  react-dom: 19.2.0
  sort-package-json: 3.4.0
  turbo: 2.6.0
  tyme4ts: 1.3.9
  typescript: 5.9.3
  vitest: 4.0.7
  vitest-browser-react: 2.0.2
  ahooks: 3.9.6
