packages:
  - apps/*
  - packages/*
  - "!**/test/**"
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - lefthook
catalog:
  "@biomejs/biome": 2.3.5
  "@microsoft/api-extractor": 7.55.0
  "@rsbuild/core": 1.6.5
  "@rslib/core": 0.17.1
  "@rsbuild/plugin-react": 1.4.2
  "@typescript/native-preview": 7.0.0-dev.20251112.1
  "@vitejs/plugin-react": 5.1.1
  "@vitest/browser-playwright": 4.0.9
  "@vitest/coverage-v8": 4.0.9
  "@types/react": 19.2.4
  "@types/react-dom": 19.2.3
  "@changesets/cli": 2.29.7
  lefthook: 2.0.4
  react: 19.2.0
  react-dom: 19.2.0
  sort-package-json: 3.4.0
  tyme4ts: 1.3.9
  typescript: 5.9.3
  vitest: 4.0.9
  vitest-browser-react: 2.0.2
  ahooks: 3.9.6
  is-ci: 4.1.0
