packages:
  - apps/*
  - packages/*
  - "!**/test/**"

catalog:
  "@changesets/changelog-github": 0.5.2
  "@changesets/cli": 2.29.8
  "@microsoft/api-extractor": 7.55.1
  "@moonrepo/cli": 1.41.7
  "@rsbuild/core": 1.6.11
  "@rsbuild/plugin-react": 1.4.2
  "@rslib/core": 0.18.2
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@typescript/native-preview": 7.0.0-dev.20251130.1
  "@vitejs/plugin-react": 5.1.1
  "@vitest/browser-playwright": 4.0.14
  "@vitest/coverage-v8": 4.0.14
  "@vitest/ui": 4.0.14
  ahooks: 3.9.6
  is-ci: 4.1.0
  lefthook: 2.0.4
  react: 19.2.0
  react-dom: 19.2.0
  sort-package-json: 3.5.0
  tyme4ts: 1.3.9
  typescript: 5.9.3
  vitest: 4.0.14
  vitest-browser-react: 2.0.2
  oxlint: 1.31.0
  oxlint-tsgolint: 0.8.3
  oxfmt: 0.16.0

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - lefthook
